---
Name: toastquickblocks
---
Toast\QuickBlocksExtension:
  available_blocks:
    - Toast\QuickBlocks\TextBlock
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - quickblocks/css/quickblocks.css
SilverStripe\Assets\File:
  extensions:
    - Toast\QuickBlocks\FileExtension
Toast\QuickBlocks\QuickBlock:
  better_buttons_enabled: false

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Toast\QuickBlocks\SiteTreeExtension