---
Name: toastquickblocks
After:
  - 'framework/*'
  - 'cms/*'
---
QuickBlocksExtension:
  available_blocks:
    - TextBlock

LeftAndMain:
  extra_requirements_css:
    - quickblocks/css/quickblocks.css

File:
  extensions:
    - FileExtension