---
Name: toastquickblocks
---
QuickBlocksExtension:
  available_blocks:
    - TextBlock
    - AccordionBlock
    - VideoBlock
    - ImageBlock
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - quickblocks/css/quickblocks.css
SilverStripe\Assets\File:
  extensions:
    - FileExtension
