---
Name: toastquickblocks
---
Toast\QuickBlocksExtension:
  available_blocks:
    - Toast\QuickBlocks\TextBlock
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - quickblocks/css/quickblocks.css
SilverStripe\Assets\File:
  extensions:
    - Toast\QuickBlocks\FileExtension
Toast\QuickBlocks\QuickBlock:
  better_buttons_enabled: false

# Used to remove buttons from the DataObject.
# NOTE: The documented getCMSActions and updateCMSActions do not actually work.
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    CmsActionsExtension: CmsActionsExtension
