---
Name: toastquickblocks
---
Toast\QuickBlocksExtension:
  available_blocks:
    - Toast\TextBlock
    - Toast\AccordionBlock
    - Toast\VideoBlock
    - Toast\ImageBlock
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - quickblocks/css/quickblocks.css
SilverStripe\Assets\File:
  extensions:
    - Toast\FileExtension
Toast\QuickBlock:
  better_buttons_enabled: false