<?php


namespace Toast\Extensions;

use Toast\Model\Testimonial;
use SilverStripe\Forms\FieldList;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldConfig_RelationEditor;
use UndefinedOffset\SortableGridField\Forms\GridFieldSortableRows;

class TestimonialBlockExtension extends DataExtension
{
    private static $db = [
        
    ];

    private static $many_many = [
        'Testimonials' => Testimonial::class,
    ];

    public function updateCMSFields(FieldList $fields)
    {
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub

        $fields->removeByName(['Attribution', 'Testimonial', 'Location']);

        $conf = GridFieldConfig_RelationEditor::create(10);
        $conf->addComponent(new GridFieldSortableRows('SortOrder'));
        $fields->addFieldsToTab('Root.Main', [
            GridField::create('Testimonials', 'Testimonials', $this->owner->Testimonials(), $conf)
        ]);

    }
}
